os:
  - linux
  - osx
language: node_js
node_js:
  - "10"
  - "12"
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
services:
  - docker
env:
  global:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=password
    - PGPORT=7777
    - PGDATABASE=mutation_example
    - PGHOST=localhost
    - PGPASSWORD=password
    - PGUSER=postgres

before_install:
  - yarn install
  - docker run -d -p 7777:5432 --name postgres pyramation/postgres
  - sleep 3
  - while ! docker exec -it postgres pg_isready -U postgres -h 127.0.0.1; do echo "$(date) - waiting for database to start"; sleep 1; done
  - createdb mutation_example
  - psql -f sql/roles.sql mutation_example
  - psql -f sql/user.sql mutation_example
  - psql -f sql/schema.sql mutation_example

script:
  - yarn install
  - yarn test
